import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {DEFAULT_FILTERS,complete4D,filterModels,sortModels,median,medianSet,paretoIds,deriveView,chartRows,toggleSelection,validateDataset,sanitizePreferences,toCSV,money} from '../src/core.js';
const input=JSON.parse(await readFile(new URL('../data/models.json',import.meta.url)));const data=input.models;
const r=(id,cost,intelligence,speed=100,latency=2)=>({id,cost,intelligence,speed,latency,model:id,creator:'Creator'});
test('retains 102 original rows; 96 complete; 2 rounded zeros',()=>{validateDataset(input);assert.equal(data.length,102);assert.equal(data.filter(complete4D).length,96);assert.equal(data.filter(r=>r.cost===0).length,2);});
test('case insensitive search covers creator and exact variant',()=>{assert.ok(filterModels(data,{query:'OPENAI'}).every(r=>r.creator==='OpenAI'));assert.equal(filterModels(data,{query:'GPT-6 Luna (low)'}).length,1);});
test('80 tokens/s is an actual numeric condition, not a missing select option',()=>{const result=filterModels(data,{minSpeed:'80',maxCost:'.5',minIntelligence:30,maxLatency:10});assert.ok(result.length>0);assert.ok(result.every(r=>r.speed>=80&&r.cost<=.5&&r.intelligence>=30&&r.latency<=10));});
test('missing measurements fail active constraints',()=>{const rows=[r('a',1,20,null,null),r('b',1,20,10,5)];assert.equal(filterModels(rows,{minSpeed:0}).length,1);assert.equal(filterModels(rows,{maxLatency:10}).length,1);assert.equal(filterModels(rows,{}).length,2);});
test('zero filter is not treated as empty',()=>assert.equal(filterModels(data,{maxCost:0}).length,2));
test('median handles null, odd, even and empty',()=>{assert.equal(median([]),null);assert.equal(median([1,2,5]),2);assert.equal(median([null,2,4]),3);});
test('null always sorts last in both directions',()=>{for(const direction of ['asc','desc'])assert.equal(sortModels([r('a',1,2,null),r('b',1,2,1)],'speed',direction).at(-1).id,'a');});
test('Pareto: one strict improvement; tied models retained; zero excluded',()=>{const result=paretoIds([r('a',1,2),r('b',1,2),r('c',2,1),r('d',0,99),r('e',2,4)]);assert.deepEqual([...result],['a','b','e']);});
test('full data 2D frontier is 11 positive cost rows',()=>assert.equal(paretoIds(data).size,11));
test('median scope uses base thresholds once, identical shared view membership',()=>{const filter={...DEFAULT_FILTERS,scope:'median'};const v=deriveView(data,filter);assert.deepEqual(v.rows.map(r=>r.id).sort(),[...medianSet(data).ids].sort());assert.equal(v.base.length,102);});
test('complete scope matches 4D count',()=>assert.equal(deriveView(data,{scope:'complete'}).rows.length,96));
test('log cost never plots rounded zero; cost-only does not hide partial rows',()=>{assert.equal(chartRows(data,'cost','log').length,100);assert.equal(chartRows(data,'cost','linear').length,102);assert.equal(chartRows(data,'four','log').length,94);});
test('selection limit rejects fifth without evicting first',()=>{const ids=['a','b','c','d'];assert.deepEqual(toggleSelection(ids,'e').ids,ids);assert.ok(toggleSelection(ids,'e').error);assert.deepEqual(toggleSelection(ids,'b').ids,['a','c','d']);});
test('preferences validate compare IDs, enums and negative numeric filters',()=>{const p=sanitizePreferences({theme:'evil',compareIds:['a','a','bad'],filters:{minSpeed:'80',maxCost:-1,maxLatency:null}},['a']);assert.equal(p.theme,'light');assert.deepEqual(p.compareIds,['a']);assert.equal(p.filters.minSpeed,'80');assert.equal(p.filters.maxCost,'');assert.equal(p.filters.maxLatency,'');});
test('CSV quotes and neutralizes formula prefixes',()=>{const text=toCSV([{model:'=SUM(A1)',creator:'a"b'}]);assert.ok(text.includes("'"+'=SUM(A1)'));assert.ok(text.includes('a""b'));});
test('cost precision preserved',()=>{assert.equal(money(.0045),'$0.0045');assert.equal(money(null),'—');assert.equal(money(0),'$0.00');});
test('invalid dataset rejects duplicate IDs, negative values and cost mismatch',()=>{for(const mutate of [d=>d.models[1].id=d.models[0].id,d=>d.models[0].speed=-1,d=>d.models[0].costLabel='$0.01']){const copy=structuredClone(input);mutate(copy);assert.throws(()=>validateDataset(copy));}});
